# ***Exercise 1: (Score : 1)***

# ***Exercise 1***

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [ ]:
import numpy as np

In [ ]:
# Create a numpy array containing numbers from 1 to 10
array = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_array = array.reshape(2, 5)

print(reshaped_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# ***Exercise 2: (Score : 1)***

Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [ ]:
# Create a numpy array containing numbers from 1 to 20
array = np.arange(1, 21)

# Extract elements between the 5th and 15th index (inclusive of index 5 and exclusive of index 15)
extracted_elements = array[5:15]

print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15]


# ***Exercise 3: (Score : 2)***

In [ ]:
import pandas as pd

# Create a Pandas series with the given data
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item to the series with the key 'pears' and value 4
series['pears'] = 4

print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# **Exercise 4:(Score : 2)**

Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [ ]:
import pandas as pd

# Create a DataFrame with name, age, and gender columns
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 32, 29, 45, 38, 50, 28, 24, 33, 40],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)

print(df)


      name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   29      M
3    David   45      M
4      Eva   38      F
5    Frank   50      M
6    Grace   28      F
7   Hannah   24      F
8      Ian   33      M
9     Jack   40      M


# ***Exercise 5: (Score : 1)***

Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [ ]:
import pandas as pd

# Create a DataFrame with name, age, and gender columns
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 32, 29, 45, 38, 50, 28, 24, 33, 40],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

df = pd.DataFrame(data)

# Define the occupations in a repeating pattern
occupations = ['Programmer', 'Manager', 'Analyst']

# Assign the occupations to the new 'occupation' column by repeating the list
df['occupation'] = occupations * (len(df) // len(occupations)) + occupations[:len(df) % len(occupations)]

# Print the updated DataFrame
print(df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   45      M  Programmer
4      Eva   38      F     Manager
5    Frank   50      M     Analyst
6    Grace   28      F  Programmer
7   Hannah   24      F     Manager
8      Ian   33      M     Analyst
9     Jack   40      M  Programmer


# ***Exercise 6: (Score : 1)***

Select the rows of the dataframe where the age is greater than or equal to 30.

In [ ]:
# Select rows where the age is greater than or equal to 30
age_above_30 = df[df['age'] >= 30]

# Print the filtered DataFrame
print(age_above_30)


    name  age gender  occupation
1    Bob   32      M     Manager
3  David   45      M  Programmer
4    Eva   38      F     Manager
5  Frank   50      M     Analyst
8    Ian   33      M     Analyst
9   Jack   40      M  Programmer


# ***Exercise 7: (Score : 2)***

Convert this dataframe to a csv file and read that csv file, finally display the contents

In [ ]:
import pandas as pd

# Assuming 'df' is the DataFrame created earlier
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 32, 29, 45, 38, 50, 28, 24, 33, 40],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
                   'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

# Create the DataFrame
df = pd.DataFrame(data)

# Convert the DataFrame to a CSV file (without including the index)
df.to_csv('dataframe.csv', index=False)

# Read the CSV file back into a DataFrame
df_from_csv = pd.read_csv('dataframe.csv')

# Display the contents of the DataFrame
print(df_from_csv)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   29      M     Analyst
3    David   45      M  Programmer
4      Eva   38      F     Manager
5    Frank   50      M     Analyst
6    Grace   28      F  Programmer
7   Hannah   24      F     Manager
8      Ian   33      M     Analyst
9     Jack   40      M  Programmer
